services:

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_latency_django
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - gunicorn
      - core.wsgi:application
      - --bind
      - 0.0.0.0:8000

  postgres:
    image: postgres:17-alpine
    container_name: api_latency_postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: api_latency_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_latency_celery
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    command:
      - celery
      - -A
      - core
      - worker
      - --loglevel=INFO

volumes:
  postgres_data:
  redis_data: